services:
  order-processing-worker:
    image: orderprocessorservice:latest
    build:
      context: .
      dockerfile: OrderProcessorService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LOG_LEVEL=Debug
      - LOG_NAME=OrderProcessorLog.log
      - ORDERS_URL=https://orders-api.com/orders
      - ALERTS_URL=https://alert-api.com/alerts
      - UPDATES_URL=https://update-api.com/update
    networks:
      - order-network

networks:
  order-network:
    driver: bridge